Models/Category.cs
namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }
    }
}

Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

Controllers/HomeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController:Controller
    {
        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;

            if (id != null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }

            return View(movies);
        }

        public IActionResult Details(int id)
        {
            // MovieCategoryModel model = new MovieCategoryModel();
            // model.Categories = CategoryRepository.Categories;
            // model.Movie = MovieRepository.GetById(id);

            return View(MovieRepository.GetById(id));
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController:Controller
    {
        public IActionResult Index()
        {
            //TODO: Implement Realistic Implementation
            return View();
        }

        public IActionResult Create()
        {
            //TODO: Implement Realistic Implementation
            return View();
        }

        public IActionResult Details()
        {
            //TODO: Implement Realistic Implementation
            return View();
        }

        public IActionResult List()
        {
            //TODO: Implement Realistic Implementation
            return View();
        }
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            // home/index/3
            // {controller}/{action}/{id?}
            // RouteData.Values["controller"] => home
            // RouteData.Values["action"] => index
            // RouteData.Values["id"] => 3

            if (RouteData.Values["action"].ToString() == "Index")
                ViewBag.SelectedCategory = RouteData?.Values["id"];

            return View(CategoryRepository.Categories);
        }
    }
}

Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

Views/Home/Details.cshtml
@model Movie

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
         <div class="card mb-3">

              <div class="card-body">
                   <div class="row no-gutter">
                         <div class="col-md-4">
                            <img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img">
                        </div>
                        <div class="col-md-8">
                        
                                <h5 class="card-title">
                                <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id">  @Model.Name</a> 
                                </h5>
                                <p class="card-text">
                                     @Html.Raw(Model.Description)
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">3 days ago</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_movies", Model)
    </div>
</div>

Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@if(Model.Count()!=0)
{
        @foreach (var movie in Model)
        {
            <div class="card mb-3">
                <div class="row no-gutter">
                    <div class="col-md-3">
                        <img src="~/img/@movie.ImageUrl" alt="@movie.Description" class="card-img">
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">
                            <a asp-action="Details" asp-controller="Home" asp-route-id="@movie.Id">  @movie.Name</a> 
                            </h5>
                            <p class="card-text">
                                @movie.ShortDescription
                            </p>
                            <p class="card-text">
                                <small class="text-muted">3 days ago</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        }    
}
else {
    <div class="alert alert-primary">
        <span>Seçilen kategoride film bulunmamaktadır.</span>
    </div>
}

Views/Movie/Details.cshtml
<h1>Movie/Details</h1>

Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

Views/Movie/List.cshtml
<h1>Movie/List</h1>

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">

    <a href="/" class="list-group-item list-group-item-action">
             Tüm Kategoriler
    </a>
    @foreach (var i in Model)
    {
        <a 
            asp-controller="Home" 
            asp-action="Index" 
            asp-route-id="@i.Id"
            class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==i.Id.ToString()?"active":"")">
                @i.Name
        </a>
    }   
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <title>Movie App</title>
</head>
<body>

    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>

    
</body>
</html>

Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Place footer content here.
        </span>
    </div>
</div>

Views/Shared/_menu.cshtml
@model IEnumerable<Category>

<div class="list-group">

    @foreach (var i in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@i.Name</a>
    }   
    
</div>

Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
              <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>